POST http://127.0.0.1:8080/
Content-Type: application/json

{
  "service":"demo.api.UserService",
  "methodSign":"findById@1_int",
  "args": [100]
}

//{
//  "service":"demo.api.UserService",
//  "methodSign":"findById@2_int_java.long.long.String",
//  "args": [100,"Chasen"]
//}