server:
  port: 8088

chasenrpc:
  zk:
    server: 127.0.0.1:2181
    root: chasenrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 33 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

ck:
  servers: http://127.0.0.1:8484

logging:
  level:
    root: error
    cn.chasen.rpc: debug