server:
  port: 8088

chasenrpc:
  providers: http://127.0.0.1:8081,http://127.0.0.1:8082


rpc:
  zkServer: 127.0.0.1:2181
  zkRoot: rpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  grayRatio: 10  #0-100