server:
  port: 8081
rpc:
  zkServer: 127.0.0.1:2181
  zkRoot: rpc

app:
  id: app1
  namespace: public
  env: dev
  metas: "{'gray': 'false', 'dc':'bj', 'unit':'B001'}"
logging:
  level:
    root: error
    cn.chasen.rpc: debug