server:
  port: 8081

chasenrpc:
  zk:
    server: 127.0.0.1:2181
    root: chasenrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 25

ck:
    servers: 127.0.0.1:8484

logging:
  level:
    root: error
    cn.chasen.rpc: info

app:
  id: app1
apollo:
  cacheDir: /Users/chasen/app/apollo/apollo-quick-start-2.2.0/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: false